name: dentiste
description: "Votre description ici"
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.6
  cupertino_icons: ^1.0.6
  flutter_test:
    sdk: flutter
  shared_preferences: ^2.2.3
  flutter_datetime_picker: ^1.5.1
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.3
  uuid: ^4.4.0
  firebase_messaging: ^14.9.2

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"





  

flutter:
  uses-material-design: true

  # Définition de l'icône de l'application
  

  # Déclaration des assets
  assets:
    - assets/dentiste.png
    - assets/logo.png
    - assets/user_avatar.png
    - assets/dz.PNG
    - assets/dentiste.png
    - assets/one.jpg
    - assets/deux.jpg
    - assets/dentistease.png 
    - assets/dent.jpg
    - assets/1.png
    - assets/téléchargement.jpg
    - assets/profil.png
    - assets/icon.jpg
    - assets/profiluf.png
    - assets/profiluh.png
    - assets/profildrf.png
    - assets/profildrh.png
    - assets/premier.png
