// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwlRAVWFQKxbaMtu265s1BLKjQYylKtnA',
    appId: '1:683861830861:web:7ed82d995b96bf38818d84',
    messagingSenderId: '683861830861',
    projectId: 'dentiste-new',
    authDomain: 'dentiste-new.firebaseapp.com',
    storageBucket: 'dentiste-new.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7oybPw6mgmj84fGk5Vin031wAlE_GRzM',
    appId: '1:683861830861:android:a90e730449f4ceaf818d84',
    messagingSenderId: '683861830861',
    projectId: 'dentiste-new',
    storageBucket: 'dentiste-new.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIcNcFCiFdsAkMjKLPhisR5KoYtZfJMBk',
    appId: '1:683861830861:ios:b3612af95e75a0aa818d84',
    messagingSenderId: '683861830861',
    projectId: 'dentiste-new',
    storageBucket: 'dentiste-new.appspot.com',
    iosBundleId: 'com.example.dentiste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIcNcFCiFdsAkMjKLPhisR5KoYtZfJMBk',
    appId: '1:683861830861:ios:b3612af95e75a0aa818d84',
    messagingSenderId: '683861830861',
    projectId: 'dentiste-new',
    storageBucket: 'dentiste-new.appspot.com',
    iosBundleId: 'com.example.dentiste',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwlRAVWFQKxbaMtu265s1BLKjQYylKtnA',
    appId: '1:683861830861:web:37d0949dc83ec870818d84',
    messagingSenderId: '683861830861',
    projectId: 'dentiste-new',
    authDomain: 'dentiste-new.firebaseapp.com',
    storageBucket: 'dentiste-new.appspot.com',
  );

}